### ISSUE TITLE
Implement models inherited from Document

### ISSUE THREAD

**Issue by fatawesome** [fatawesome/libinno#2]
- [ ] Book
- [ ] Article
- [ ] Audio
- [ ] Video

**Comment by BananaAndBread** [comment]
Do we bind the book and other required models to the django.auth internal User model, or do we subclass somewhere in the other place?

If the former - how do we store the user's role? Is there an internal django mechanism for that?

**Comment by fatawesome** [comment]
As mentioned in issue#1 Django has Users and Groups implementation by default. On the nearest meet-up we will decide how do we bind the document with the user.

**Comment by fatawesome** [comment]
Closed without commit because it was done.
